// Generated by CoffeeScript 1.7.1
(function() {
  var SERVER, app, express, jsonRoutes;

  SERVER = {
    host: '0.0.0.0',
    port: 8080
  };

  express = require('express');

  jsonRoutes = require('./jsonRoutes');

  app = express.createServer();

  app.configure(function() {
    return app.use(express["static"](__dirname + '/public'));
  });

  jsonRoutes.setAPI(app);

  app.listen(SERVER.port, SERVER.host);

  console.log("Worker started at " + SERVER.host + ":" + SERVER.port + " | PID: " + process.pid);

}).call(this);

//# sourceMappingURL=index.map
