// Generated by CoffeeScript 1.7.1
(function() {
  var handlers, _;

  _ = require('underscore');

  handlers = {
    test: function(req, res) {
      return res.send('DONE');
    }
  };

  this.setAPI = function(app) {
    var handler, query, _results;
    _results = [];
    for (query in handlers) {
      handler = handlers[query];
      _results.push(app.get('/' + query, handler));
    }
    return _results;
  };

}).call(this);

//# sourceMappingURL=jsonRoutes.map
